---
- name: "Store: Install thanos store systemd file"
  template:
    src: thanos-store.j2
    dest: /etc/systemd/system/thanos-store.service
  register: store_systemd
  notify: restart thanos-store

- name: "Store: Reload systemd if thanos store changed"
  systemd:
    daemon_reload: true

- name: "Store: Add defaults file"
  template:
    src: thanos-store-defaults.j2
    dest: /etc/default/thanos-store
  notify: restart thanos-store

- name: "Store: generate configuration file"
  template:
    group: prometheus
    src: thanos-s3-config.j2
    dest: "{{ thanos_store_config_file }}"
  notify: restart thanos-store

- name: "Store: Ensure thanos-store is started"
  service:
    name: thanos-store
    enabled: true
    state: started

- name: "Check if node exporter directory exists"
  stat:
    path: /etc/prometheus-node-exporter
  register: node_exporter

- name: "Add node exporter files"
  when: node_exporter.stat.exists is defined and node_exporter.stat.exists
  block:
    - set_fact: service_name="thanos-store"

    - name: "Add the node exporter file to path"
      template:
        src: node-exporter.sh.j2
        dest: /usr/local/bin/prometheus-service-restart.sh
        owner: root
        group: root
        mode: 0775

    - name: "Set up cronjob for node exporter"
      cron:
        name: "Run systemd restart count"
        minute: "*/1"
        job: "/usr/local/bin/prometheus-service-restart.sh"
